### PR TITLE
Adds endBlock param

### PR DESCRIPTION
**Pull request by alex-miller-0**
Grid+ would very much like to have an `endBlock` param to clearly define a duration for the sale.

This PR adds `endBlock`, which is initially set to an arbitrarily large block number (`9999999999999`) and can be changed by the `owner` as until the contract gets frozen.

I have added two unit tests, but would ideally like to test this in a simulation as well. That will take a bit longer, but I wanted to put this in front of you now in case you had thoughts on design.

### CODE REVIEW

**Comment by alex-miller-0** [comment]
This should be good to merge. Please review.

**Comment by skmgoldin** [comment]
1. Lets pass in the endblock param as a constructor argument. It can be added to the `sale.json` config file (default to a high number) and passed in during the migration.
2. Why the separate test file?

**Comment by alex-miller-0** [comment]
1. Couldn't fit it in the constructor. It runs out of gas.
2. Thought it would be easier because there were two contrasting end points once the sale began. In your `sale.js` you want to run the sale to exhaustion (i.e. sell all tokens). This is incompatible with testing that it has reached `endBlock`

**Comment by skmgoldin** [comment]
That's funny. I did a test last night where I added it to the constructor and it worked. I'll pull this and see what I can do.

**Comment by skmgoldin** [comment]
I have it working on my machine. I'm just gonna see if I can figure out a way to pull your tests into the main test file then I'll push.

**Comment by alex-miller-0** [comment]
It doesn't look like it's possible for the `owner` to withdraw unsold tokens. I'm going to add that as well.

**Comment by skmgoldin** [comment]
Could you make a separate PR for it?

**Comment by alex-miller-0** [comment]
Yep, just opened, referenced above.

**Comment by skmgoldin** [comment]
@alex-miller-0 merge this PR to your master, then I'll give a thumbs up to merging this PR to @GNSPS master. https://github.com/GridPlus/simple-token-sale/pull/1

**Comment by skmgoldin** [comment]
Hey Alex, it's going to be hard to merge this PR since it's on your master branch and new commits are being added to it. Could you remake it from a dedicated branch?

**Comment by alex-miller-0** [comment]
Sorry about that. See #3 - I'll close this one.

**Pull request closed without merging**
