### PR TITLE
Add endBlock param

### PR DESCRIPTION
**Pull request by alex-miller-0**
Replaces #1 with a new branch. Please reference discussion there.

### CODE REVIEW

**Comment by skmgoldin** [comment]
Thanks @alex-miller-0. @GNSPS this gets a 👍 from me.

**Comment by GNSPS** [comment]
All looking good! But tests are giving me an error:
`Error: Invalid number of arguments to Solidity function`

Running smoothly on your end?

**Comment by alex-miller-0** [comment]
I did a fresh install on this branch and ran `npm run test` - everything passes for me. 

I have Truffle v3.4.4, npm v5.3.0, node v8.2.1

What circumstances bring you the error?

**Comment by GNSPS** [comment]
Indeed with Truffle v3.4.4 every test is passing.

I'm guessing this is a web3 issue as described here: https://github.com/trufflesuite/truffle/issues/526

Merging this PR (and leaving the note that these contracts won't compile with any Truffle version above v3.4.4)

**Pull request merged**
